apiVersion: apps/v1
kind: Deployment
metadata:
  name: dir-watcher
  labels:
    app: dir-watcher
    partOf: tombabot
    type: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dir-watcher
  template:
    metadata:
      labels:
        app: dir-watcher
        partOf: tombabot
        type: worker-app
    spec:
      containers:
      - name: dir-watcher
        image: dir-watcher:nodescript # named when building the Dockerfile
        imagePullPolicy: Never # use local image
        volumeMounts:
        - name: nfs-client
          mountPath: /mnt/camstorage # where to mount the store in the pod
        env:
        - name: NFS_PATH # used by the app to know where to watch
          value: /mnt/camstorage
        envFrom:
          - configMapRef:
              name: dir-watcher-config # external configfile
      volumes:
      - name: nfs-client
        nfs: # ip and path for the nfs storage
          server: 192.168.2.30
          path: /mnt/user/camstorage